import type { Metadata } from "next";
import { Parkinsans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { MessageCircle } from "lucide-react";

const parkinsans = Parkinsans({
  variable: "--font-parkinsans",
  subsets: ["latin"],
  adjustFontFallback: false,
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${parkinsans.variable} h-full antialiased`}>
      <body suppressHydrationWarning className={`${parkinsans.className} min-h-full flex flex-col font-sans`}>
        <Navbar />
        {children}
        <a
  href="https://wa.me/923236304752"
  target="_blank"
  rel="noopener noreferrer"
  aria-label="Chat on WhatsApp"
  className="
    group fixed bottom-5 right-5 z-[9999]
    flex h-12 w-12 items-center justify-center
    rounded-full
    bg-[#25D366]
    text-white
    shadow-[0_10px_25px_rgba(37,211,102,0.35)]
    transition-all duration-300
    hover:-translate-y-1 hover:scale-105
    hover:bg-[#20BA5A]
    hover:shadow-[0_15px_35px_rgba(37,211,102,0.5)]
    sm:h-auto sm:w-auto
    sm:gap-2.5 sm:px-6 sm:py-3
  "
>
  <span
    className="
      absolute inset-0 -z-10
      rounded-full
      bg-[#25D366]
      opacity-40
      animate-ping
    "
  />

  <MessageCircle
    className="
      h-5 w-5
      transition-transform duration-300
      group-hover:scale-110
    "
    strokeWidth={2.5}
  />

  <span className="hidden sm:inline font-semibold">
    Chat with us
  </span>
</a>

<Footer/>
      </body>
    </html>
  );
}